/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jh9KPigqw1R
 */
import Image from "next/image";


export function Project() {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-4 min-h-screen">
      <div className="group transform transition-transform duration-200 hover:scale-105 hover:shadow-lg">
        <Image
          alt="Projet pokemon"
          className="w-full h-60 object-cover rounded-lg"
          height="200"
          src="/pokemon.png"
          style={{
            aspectRatio: "300/200",
            objectFit: "cover",
          }}
          width="300"
        />
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Project 1</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
              Mon projet a consisté à développer une application web de gestion de Pokémon en utilisant le langage de programmation PHP et la base de données SQLite. J&apos;ai utilisé la librairie de sécurité Breeze pour permettre aux utilisateurs de se connecter ou de s&apos;inscrire pour débloquer certaines fonctionnalités. L&apos;application permet aux utilisateurs de rechercher, d&apos;ajouter et de classer leurs Pok&eacute;mon favoris, ainsi que de voir les statistiques détaillées de chaque Pok&eacute;mon.
          </p>
        </div>
      </div>
      <div className="group transform transition-transform duration-200 hover:scale-105 hover:shadow-lg">
        <Image
          alt="Space invader"
          className="w-full h-60 object-cover rounded-lg"
          height="200"
          src="/spaceInvader.jpeg"
          style={{
            aspectRatio: "300/200",
            objectFit: "cover",
          }}
          width="300"
        />
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Space invader</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
              Notre projet en groupe a consisté à développer une version du célèbre jeu &ldquo;Space Invaders&rdquo; en utilisant le langage de programmation Java. Nous avons travaillé en équipe pour mettre en place le code de base du jeu. Nous avons travaillé sur la conception du jeu, en créant des graphiques personnalisés et en implémentant des fonctionnalités telles que des niveaux de difficulté différents et un système de score. Nous sommes fiers du résultat final.
          </p>
        </div>
      </div>
      <div className="group transform transition-transform duration-200 hover:scale-105 hover:shadow-lg">
        <Image
          alt="Galerie d'art"
          className="w-full h-60 object-cover rounded-lg"
          height="200"
          src="/galerie_art.png"
          style={{
            aspectRatio: "300/200",
            objectFit: "cover",
          }}
          width="300"
        />
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Galerie d&apos;art</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
              Notre projet en groupe a consisté à développer une application web d&apos;une galerie d&apos;art en utilisant le langage de programmation PHP. J&apos;ai travaillé sur la partie backend du projet en collaboration avec d&apos;autres membres de l&apos;équipe, en mettant en place les fonctionnalités de gestion des artistes, des œuvres d&apos;art, d&apos;aimer une œuvre, de trier les œuvres. Pendant ce temps, d&apos;autres membres de l&apos;équipe ont travaillé sur la partie frontend de l&apos;application, en utilisant des technologies telles que HTML, CSS et JavaScript pour créer une interface attrayante et intuitive. Nous avons travaillé en étroite collaboration pour assurer la bonne intégration de la partie backend et frontend de l&apos;application. Nous sommes fiers du résultat final.
          </p>
        </div>
      </div>
    </section>
  )
}
